--- 
# Configuration of the networking group. Map networking group to the roles performed by the group here
- name: Configure networking devices
  hosts: networking
  roles: 
    - common
    - router 

  module_defaults:
   vyos.vyos.vyos_config:
    save: true