---
# Main tasks to perform on workstations

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Git if not present
  become: true
  apt:
    name: git
    state: present

- name: Load secured variables for Git Configuration
  include_vars:
    file: ~/JAM-Ansible/inventory/production/host_vars/desktop01/vault.yml

- name: Check Global Git Email
  ansible.builtin.shell:
    cmd: git config --global user.email || echo "undefined"
  register: current_git_email
  changed_when: "current_git_email.stdout != git_email"
  notify: "Set Global Git Email"

- name: Check Global Git username
  ansible.builtin.shell:
    cmd: git config --global user.name || echo "undefined"
  register: current_git_user
  changed_when: current_git_user.stdout != git_user
  notify: "Set Global Git Username"

- name: Install whois package for Ubuntu
  become: true
  ansible.builtin.apt:
    name: whois
    state: present

- name: Check if Homebrew is installed
  stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: brew_stat

- name: Install Homebrew
  become: true
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when:
    not brew_stat.stat.exists

- name: Add Homebrew to PATH and shell env
  become: true
  ansible.builtin.lineinfile:
    path: "{{ kubernetes_admin_dir }}/.bashrc"
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
    state: present
    insertafter: EOF
  loop:
    - "{{ kubernetes_admin_user }}"

- name: Run terraform tasks
  ansible.builtin.include_tasks:
    file: terraform.yml

- name: Run kubernetes tasks
  ansible.builtin.include_tasks:
    file: kubernetes.yml