---
# Terraform tasks to perform on wsl workstations

- name: Ensure prerequiste packages are installed and updated
  become: true
  apt:
    name:
    - gnupg
    - software-properties-common
    - curl
    state: present
    update_cache: yes

- name: Check if HashiCorp GPG key exists
  stat:
    path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  register: hashicorp_gpg_key

- name: Install HasiCorp GPG key
  become: true
  shell: wget -O- https://apt.releases.hashicorp.com/gpg | \
         gpg --dearmor | \
         sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
  when: not hashicorp_gpg_key.stat.exists
  
- name: Install HashiCorp repo
  become: true
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_facts.distribution_release }} main"
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Terraform
  become: true
  apt:
    name: terraform
    state: present

- name: Verify Terraform installation
  command: terraform --version
  register: terraform_version_check

- name: Show installed Terraform version
  debug:
    msg: "Terraform {{ terraform_version_check.stdout }} installed successfully."  

- name: Install Packer
  become: true
  apt:
    name: packer
    state: present

- name: Verify Packer installation
  command: packer --version
  register: packer_version_check

- name: Show installed Packer version
  debug:
    msg: "Packer {{ packer_version_check.stdout }} installed successfully."