---
#YAML inventory file for production hosts. Classify hosts based on groups here
networking:
  hosts:
    vyos01:
      ansible_host: 10.0.1.1

workstation-wsl:
  hosts:
    desktop01:
      ansible_host: localhost

server:
  children:
    nas_server:
      hosts:
        nas01:
          ansible_host: 10.0.10.84
    kube_control:
      hosts:
        control-k8s01:
          ansible_host: 10.0.10.2
    kube_node:
      hosts:
        node-k8s01:
          ansible_host: 10.0.10.3
        node-k8s02:
          ansible_host: 10.0.10.4