---
#YAML inventory file for production hosts. Classify hosts based on groups here
networking:
  hosts:
    vyos01:
      ansible_host: 10.0.1.1

workstation-wsl:
  hosts:
    desktop01:
      ansible_host: localhost

server:
  hosts:
    nas01:
      ansible_host: 10.0.10.84