---
# Main tasks to perform on servers

- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Run NFS Server tasks for NAS servers
  ansible.builtin.include_tasks:
    file: prod_nfs_server.yml
  when: "'nas_server' in group_names"

- name: Run NFS Client tasks for non NAS servers
  ansible.builtin.include_tasks:
    file: prod_nfs_client.yml
  when: "'nas_server' not in group_names"

- name: Run Kubernetes tasks for kubernetes hosts
  ansible.builtin.include_tasks:
    file: prod_kube_all.yml
  when: group_names | select('search','kube') | list | count > 0
