---
# Tasks to install and configure NFS clients

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Install NFS client packages
  become: true
  ansible.builtin.apt:
    name: nfs-common
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Create the mount directory if it doesn't exist
  become: true
  ansible.builtin.file:
    path: /mnt/media
    state: directory
    mode: '0755'

- name: Add NFS share to /etc/fstab for persistent mounting
  become: true
  ansible.builtin.mount:
    path: /mnt/media
    src: 10.0.10.84:/srv/nfs/media
    opts: rw,sync,hard,
    state: mounted
    fstype: nfs