---
# Tasks to create kubernetes cluster on control nodes. This playbook should only run if no clusters exists.

- name: Create kubernetes cluster
  become: true
  ansible.builtin.command:
    cmd: kubeadm init --pod-network-cidr 10.244.0.0/16

- name: Create ~/.kube directory
  become: true
  ansible.builtin.file:
    path: "{{ kubernetes_admin_user }}/.kube"
    state: directory
    mode: '0755'

- name: Configure kubectl for cluster administrator users
  become: true
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ kubernetes_admin_dir }}/.kube/config"
    remote_src: true
    owner: "{{ kubernetes_admin_user }}"
    group: "{{ kubernetes_admin_user }}"
    mode: preserve

- name: Install Calico for networking kubernetes cluster pods
  become: true
  ansible.builtin.command:
    cmd: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/custom-resources.yaml

#- name: Configure kubectl for cluster administrator users
#  become: yes
#  ansible.builtin.shell: |
#    - mkdir -p {{ kubernetes_admin_dir }}/.kube
#    - sudo cp -i /etc/kubernetes/admin.conf {{ kubernetes_admin_dir }}/.kube/config
#    - sudo chown $(id -u {{ kubernetes_admin_user }}):(id -g {{ kubernetes_admin_user }}) {{ kubernetes_admin_dir }}/.kube/config
