---
# Tasks to install and configure NFS server

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: yes
    
- name: Ensure NFS utilities are installed
  become: true
  ansible.builtin.apt:
    name:
    - nfs-common
    - nfs-kernel-server
    state: present

- name: Create Export Directory for media service
  become: true
  ansible.builtin.file:
    path: /srv/nfs/jellyfin
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure NFS exports
  become: true
  ansible.builtin.blockinfile:
    path: /etc/exports
    block: |
      /srv/nfs/jellyfin 10.0.10.0/24(rw,sync,no_subtree_check)
    state: present

- name: Check if /srv/nfs/jellyfin is already exported
  become: true
  ansible.builtin.shell:
    cmd: exportfs -v | grep '/srv/nfs/jellyfin'
  register: nfs_media_exported
  changed_when: nfs_media_exported.stdout == ''
  failed_when: false
  notify: "Export Shared Directory"

- name: Ensure NFS server is running and enabled at boot
  become: true
  ansible.builtin.systemd:
    name: nfs-kernel-server
    enabled: yes
    state: started

- name: Create NFS directory structure for media service
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /srv/nfs/jellyfin/config/
    - /srv/nfs/jellyfin/media/
    - /srv/nfs/jellyfin/media/Movies/
    - /srv/nfs/jellyfin/media/TVShows/