---
# Main tasks to perform for routers.

- name: Set Timezone
  vyos.vyos.vyos_config:
    lines:
    - set system time-zone Australia/Melbourne

- name: Configure WAN interface
  vyos.vyos.vyos_config:
    lines:
    - set interfaces ethernet {{ wan_interface }} address dhcp
    - set interfaces ethernet {{ wan_interface }} description WAN

- name: Set NTP server
  vyos.vyos.vyos_config:
    lines:
    - set service ntp server 0.au.pool.ntp.org

- name: Configure name servers
  vyos.vyos.vyos_system:
    name_servers:
    - 1.1.1.1
    - 1.0.0.1 

- name: Configure user SSH authentication
  vyos.vyos.vyos_config:
    lines:
    - set system login user vyos authentication public-keys jamiesonwilliams4@gmail.com type ssh-ed25519
    - set system login user vyos authentication public-keys jamiesonwilliams4@gmail.com key "{{ lookup('ansible.builtin.file', ssh_public_key_file) }}"
    - set service ssh disable-password-authentication

- name: Run prod_core_01 task
  ansible.builtin.include_tasks:
    file: prod_core_01.yml
  when: inventory_hostname == "vyos01"
  
- name: Run prod_core_vlan for vlan configuration
  ansible.builtin.include_tasks:
    file: prod_core_vlan.yml

- name: Run prod_core_bgp for bgp configuration
  ansible.builtin.include_tasks:
    file: prod_core_bgp.yml